ci: # the pre-commit ci bot on github does not like repo: local
    skip: [pylint, black, mypy, pytest]
    autofix_prs: false

default_language_version:
  python: python3.9
exclude: |
  (?x)^(
      ankimorphs/ui/.*|
      tests/data/morphemizers/.*|
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
        args: ['--enforce-all']
        exclude: |
          (?x)^(
              docs/src/frequency_lists/.*|
              docs/src/img/revert_changes.mp4|
              docs/src/img/note-type.mp4|
              docs/src/img/deck-options.mp4|
              docs/src/img/learn-now.mp4|
              docs/src/img/adding-extra-fields.mp4|
              tests/data/card_collections/big-japanese-collection.anki2|
              tests/data/populated_ankimorphs.db|
          )$
      - id: check-case-conflict
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix']
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: name-tests-test
        files: '^tests'
        exclude: |
          (?x)^(
              ^tests/environment_setup_for_tests.py|
              ^tests/README.md|
              ^tests/data/.*|
          )$
      - id: requirements-txt-fixer
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        exclude: |
          (?x)^(
              tests/.*|
              docs/src/frequency_lists/.*|
          )$
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-type-ignore
      - id: python-use-type-annotations
      - id: python-check-mock-methods
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
        files: 'ankimorphs/|^tests/'
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        files: 'ankimorphs/|^tests/'
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.11
    hooks:
      - id: vulture
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        require_serial: true
        types: [ python ]
        files: 'ankimorphs/|^tests/'
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        files: 'ankimorphs/|^tests/'
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [ python ]
        files: 'ankimorphs/|^tests/'
        exclude: |
          (?x)^(
              ^tests/.*|
          )$
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
